name: rebuy
description: ReBuy - GetX Flutter app integrated with MongoDB (via Node/Express API)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
